name: Node CI

on:
  push:
    paths-ignore:
      - docusaurus/**/*

jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["14", "16"]
    name: "[v${{ matrix.node-version }}] prepare"

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ github.sha }}-node_modules-v${{ matrix.node-version }}

  check:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        node-version: ["14", "16"]
    name: "[v${{ matrix.node-version }}] check"

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        uses: bahmutov/npm-install@v1

      - name: Next.js cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs

      - name: Lint
        run: |
          yarn run lint

      # - name: Test
      #   env:
      #     CI: 1
      #   run: |
      #     yarn t

      - name: Submit coverage
        uses: codecov/codecov-action@v1

  build-and-run:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        node-version: ["14", "16"]
    name: "[v${{ matrix.node-version }}] build"

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        uses: bahmutov/npm-install@v1

      - name: Next.js cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs

      - name: Build
        env:
          SITE_URL: http://localhost:3000
        run: |
          yarn run build

      - name: Run & check status code
        run: |
          yarn start &
          sleep 5
          curl http://localhost:3000 > /dev/null
